### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by wazapenJr** [indiecastfm/react-native-audio-streamer#26]
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [:react-native-audio-streamer] AndroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-24:19 to override.

**Comment by cinder92** [comment]
@wazapenJr  have you found solution?

**Comment by cinder92** [comment]
i just found the solution



You have to tell the compiler to ignore the attribute from the external library. The way to do that is to add this line in application tag:

`tools:replace="android:allowBackup"`

PS: To access the tools add xmlns:tools="http://schemas.android.com/tools" in the manifest tag at the top.

**Comment by ithustle** [comment]
@cinder92 did you build succeed in iOS ? I'm getting the following:
`Typedef redefinition with different types ('struct (anonymous struct at /Users/celiogarcia/Library/Developer/Xcode/DerivedData/bolada-ebkywcqdszgvdfcgcaqmidzuhhnk/Build/Products/Debug-iphonesimulator/include/React/RCTBridgeModule.h:52:16)' vs 'struct RCTMethodInfo') `
